name: torque_hours_x
description: "An app written in flutter to manage Texas Torque members' hours."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Market Deco
      fonts:
        - asset: assets/fonts/Market_Deco.ttf
  assets:
    - assets/imgs/torque_logo.png