// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvYxVHbIWFU7G1LrgwRa08H-mGcagUBM',
    appId: '1:219279638903:web:411144db36f049c4e76172',
    messagingSenderId: '219279638903',
    projectId: 'torque-hours-x',
    authDomain: 'torque-hours-x.firebaseapp.com',
    storageBucket: 'torque-hours-x.appspot.com',
    measurementId: 'G-4195GYHJGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTJukGQ_7YhHX2B6WSK4U1W-cgIC6Rao',
    appId: '1:219279638903:android:d89b86f76041d7f4e76172',
    messagingSenderId: '219279638903',
    projectId: 'torque-hours-x',
    storageBucket: 'torque-hours-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaR3fig9JN5GVWHVHGfQtIW8gf8MIrt_8',
    appId: '1:219279638903:ios:acaa7590eb8fb71fe76172',
    messagingSenderId: '219279638903',
    projectId: 'torque-hours-x',
    storageBucket: 'torque-hours-x.appspot.com',
    iosBundleId: 'com.example.torqueHoursx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaR3fig9JN5GVWHVHGfQtIW8gf8MIrt_8',
    appId: '1:219279638903:ios:acaa7590eb8fb71fe76172',
    messagingSenderId: '219279638903',
    projectId: 'torque-hours-x',
    storageBucket: 'torque-hours-x.appspot.com',
    iosBundleId: 'com.example.torqueHoursx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdvYxVHbIWFU7G1LrgwRa08H-mGcagUBM',
    appId: '1:219279638903:web:639760f4b731fbf6e76172',
    messagingSenderId: '219279638903',
    projectId: 'torque-hours-x',
    authDomain: 'torque-hours-x.firebaseapp.com',
    storageBucket: 'torque-hours-x.appspot.com',
    measurementId: 'G-7NV74HTG02',
  );
}
